name: scheduler
description: An event-tracking app.

publish_to: 'none' 

version: 1.0.2+2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.4
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  rxdart: ^0.27.7
  intl: ^0.17.0
  quickalert: ^1.0.1
  flutter_colorpicker: ^1.0.3
  stacked_card_carousel: ^0.0.4
  flutter_svg: ^1.1.6
  rect_getter: ^1.1.0
  date_time_picker: ^2.1.0
  flutter_alarm_clock: ^0.0.2
  easy_localization: ^3.0.1
  firebase_core: ^2.7.1
  firebase_analytics: ^10.1.5
  share_plus: ^6.3.1
  url_launcher: ^6.1.10
  platform_device_id: ^1.0.1

  cupertino_icons: ^1.0.2
  flutter_gen: ^5.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  build_runner: ^2.2.0  
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter_native_splash:  
  image: assets/images/app_icon.png
  color: "#297373"

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/translations/

  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
  
